image: debian/stable
oauth: pages.sr.ht/PAGES:RW
environment:
    SITE: rabbits.srht.site/potato
sources:
    - https://git.sr.ht/~rabbits/potato
tasks:
    - prepare: |
        curl -fsS https://rabbits.srht.site/uxn/uxn-lin64.tar.gz | tar -zx
    - build: |
        cd potato
        cat src/main.tal src/manifest.tal src/desktop.tal src/apps.tal src/assets.tal > bin/potato.tal
        ../uxn/uxnasm bin/potato.tal ../potato.rom
    - upload: |
        tar -czf out.tar.gz potato.rom
        acurl() {
            set +x
            curl -H "Authorization: Bearer ${OAUTH2_TOKEN}" "${@}"
            set -x
        }
        acurl -fsS "https://pages.sr.ht/publish/${SITE}" -Fcontent=@out.tar.gz
        acurl -fsS "https://pages.sr.ht/publish/${SITE}" -Fcontent=@out.tar.gz -Fprotocol=GEMINI
